### ISSUE TITLE
Better error stack

### ISSUE THREAD

**Issue by kilianc** [tj/co#125]
Currently

```
Error: yield a function, promise, generator, array, or object
```

has a stack like this

``` js
"stack": [
    "Error: yield a function, promise, generator, array, or object",
    "    at next (/my/project/api/node_modules/koa/node_modules/co/index.js:115:12)",
    "    at Object.<anonymous> (/my/project/api/node_modules/koa/node_modules/co/index.js:56:5)",
    "    at next (/my/project/api/node_modules/koa/node_modules/co/index.js:99:21)",
    "    at Object.<anonymous> (/my/project/api/node_modules/koa/node_modules/co/index.js:56:5)",
    "    at next (/my/project/api/node_modules/koa/node_modules/co/index.js:99:21)",
    "    at Object.<anonymous> (/my/project/api/node_modules/koa/node_modules/co/index.js:56:5)",
    "    at next (/my/project/api/node_modules/koa/node_modules/co/index.js:99:21)",
    "    at Object.<anonymous> (/my/project/api/node_modules/koa/node_modules/co/index.js:56:5)",
    "    at Object.next (/my/project/api/node_modules/koa/node_modules/co/index.js:99:21)",
    "    at /my/project/api/node_modules/koa/node_modules/co/index.js:102:18"
  ]
```

It's mostly impossible to debug, maybe we can manipulate original stack or attach a new one?

**Comment by kgdev** [comment]
just find that using "yield *" will keep the stack trace. have a try.

**Comment by jonathanong** [comment]
PR welcomed. i'm not sure how this solve this particular case.
