### ISSUE TITLE
Consistent stack traces

### ISSUE THREAD

**Issue by madbence** [tj/co#188]
My problem is that if my `Error` is not created in the context of the generator, the stack trace is missing:

```js
var co = require('co');

function* a() {
  yield* b();
}

function* b() {
  yield new Promise(function(resolve, reject) {
    setTimeout(function() {
      reject(new Error());
    }, 1000);
  });
}

co(function* () {
  try {
    yield* a();
  } catch(err) {
    console.error(err.stack);
  }
});
```

```
Error
    at null._onTimeout (...)
    at Timer.listOnTimeout (...)
```

Stack trace is just fine, if I throw in the generator:

```js
var co = require('co');

function* a() {
  yield* b();
}

function* b() {
  yield new Promise(function(resolve, reject) {
    setTimeout(function() {
      resolve();
    }, 1000);
  });
  throw new Error();
}

co(function* () {
  try {
    yield* a();
  } catch(err) {
    console.error(err.stack);
  }
});
```

```
Error
    at b (...)
    at GeneratorFunctionPrototype.next (...)
    at a (...)
    at GeneratorFunctionPrototype.next (...)
    at ...
    at GeneratorFunctionPrototype.next (...)
    at onFulfilled (...)
```

I perfectly understand that this is the correct behavior (the `setTimeout`s callback has absolutely no idea that the computation was suspended), but it is really annoying. Is there any other way to fix this other than wrapping every `Promise` in a try-catch, and wrapping the original `Error` with a new one?

```js
try {
  yield new Promise(function(resolve, reject) {
    setTimeout(function() {
      reject(new Error())
    }, 1000);
  });
} catch(e) {
  var err = new Error(e.message);
  err.original = e;
  throw err;
}
```

**Comment by jonathanong** [comment]
PR welcomed, but i'm not a big fan of manipulating stack traces

**Comment by madbence** [comment]
@jonathanong the problem is not that they are not readable, they are completely missing if they are not created in the right place (see my first example). Touching stack traces is obviously a no-go, I just want to know if there is a better workaround than the one I've presented (catching and rethrowing errors). I guess `co` itself cannot really do anything with that, but maybe there are cleaner workarounds to avoid losing stack traces.

**Comment by jonathanong** [comment]
oh sorry. no idea.

**Comment by petkaantonov** [comment]
It needs support from the promise implementation you are using, for example:

```js
var Promise = require("bluebird");
var co = require("co");
Promise.longStackTraces();

function* a() {
  yield* b();
}

function* b() {
  yield new Promise(function(resolve, reject) {
    setTimeout(function() {
      reject(new Error());
    }, 1000);
  });
}

co(function* () {
  try {
    yield* a();
  } catch(err) {
    console.error(err.stack);
  }
});
```
Gives:

```
Error
    at null._onTimeout (test.js:12:14)
    at Timer.listOnTimeout (timers.js:90:15)
From previous event:
    at b (test.js:10:9)
    at GeneratorFunctionPrototype.next (native)
    at a (test.js:6:10)
    at GeneratorFunctionPrototype.next (native)
    at test.js:19:12
    at GeneratorFunctionPrototype.next (native)
    at onFulfilled (\node_modules\co\index.js:59:19)
    at \node_modules\co\index.js:48:5
    at co (\node_modules\co\index.js:47:10)
    at Object.<anonymous> (test.js:17:1)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Function.Module.runMain (module.js:487:10)
    at startup (node.js:111:16)
    at node.js:809:3
```

Of course if you do that then you might as well do `yield Promise.delay(1000)` or even `var co = Promise.coroutine`

**Comment by madbence** [comment]
So it can't be solved without touching the stack trace :disappointed:...

`bluebird` is definitely useful for development, thanks :+1:.

**Comment by petkaantonov** [comment]
> So it can't be solved without touching the stack trace

Sure but why does it matter to you? Someone is going to have to create a stack trace somewhere, whether that's V8 or some custom library doesn't make a difference.

**Comment by madbence** [comment]
It has a huge performance impact *afaik*, and there should be meaningful stack traces in prod too.

**Comment by petkaantonov** [comment]
If V8 provided those long stack traces there would be exactly the same performance impact, that's what I mean by platform not being magical - the same logic runs through your CPU.

Also if you were using native promises then using bluebird has no performance impact as it performs same as native promises when long stack traces are enabled, or 5-10x faster when they're disabled.

**Comment by madbence** [comment]
Wow, I thought that long stack traces are much more slower than the native implementation. Thanks for the info :+1: !

**Comment by yyrdl** [comment]
I have implement  stacktrace in zco , To be honest, it's a really expensive operation,but acceptable.
