### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by zwb-ict** [tj/co#240]
I yleld a Promises in co.wrap, but it throw **TypeError: undefined is not a function**, I don't know why! Would you help me please? Thank you!

app.js:

```
app.init = co.wrap(function *(overwriteDB) {
  yield pm2.connect();

  koaConfig(app);

  app.server = app.listen(config.app.port);
  if (config.app.env !== 'test') {
    console.log('PM2 monitor listening on port ' + config.app.port);
  }
});

if (!module.parent) {
  app.init().catch(function (err) {
    console.error(err.stack);
    process.exit(1);
  });
}
```

pm2.js:

```
var _ = PM2.prototype;

exports = module.exports = PM2;

function PM2() {
  debug("PM2");
  if (!(this instanceof PM2)) return new PM2;
  this.env = process.env.NODE_ENV || 'development';
};

_.connect = function() {
  debug('connect');
  return new Promise(function(resolve, reject) {
    pm2.connect(function(err) {
      if (err) reject(err);
      resolve();
    });
  });
};
```

**Comment by bucaran** [comment]
What are these two files? What line is giving you the problem?

```js
if (!module.parent) {
// are you sure `app.init()` returns a valid object?
  app.init().catch(function (err) {
    console.error(err.stack);
    process.exit(1);
  });
}
```

**Comment by zwb-ict** [comment]
Thank you @bucaran  https://github.com/zwb-ict/pm2-monitor This is my code. 

TypeError: undefined is not a function
    at Application.<anonymous> (/Users/zwb/Documents/TalkingData/Projects/Datasync/Code/dmp/pm2-monitor/app.js:15:13)
    at GeneratorFunctionPrototype.next (native)
    at onFulfilled (/Users/zwb/Documents/TalkingData/Projects/Datasync/Code/dmp/pm2-monitor/node_modules/co/index.js:65:19)
    at /Users/zwb/Documents/TalkingData/Projects/Datasync/Code/dmp/pm2-monitor/node_modules/co/index.js:54:5
    at Application.co (/Users/zwb/Documents/TalkingData/Projects/Datasync/Code/dmp/pm2-monitor/node_modules/co/index.js:50:10)
    at Application.createPromise [as init] (/Users/zwb/Documents/TalkingData/Projects/Datasync/Code/dmp/pm2-monitor/node_modules/co/index.js:30:15)
    at Object.<anonymous> (/Users/zwb/Documents/TalkingData/Projects/Datasync/Code/dmp/pm2-monitor/app.js:26:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by zwb-ict** [comment]
@bucaran  The line 15 is: yield pm2.connect();

**Comment by bucaran** [comment]
@zwb-ict Right. So before you call `co.wrap(...)`, make sure that your module at `./server/lib/pm2.js` is returning a valid object. Perhaps `yield pm2.connect();` fails because `pm2` is an empty object and it has no `connect` method.

**Comment by zwb-ict** [comment]
@bucaran I try 
```
co(function *() {
  yield pm2.connect();
  var res = yield pm2.list();
  console.log(res);
});
```
in app.js, it works OK.
