### ISSUE TITLE
Co suppress error output on nested require

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [tj/co#242]
test.js:
```javascript
var co = require("co")
co(function()
{
  console.log("test-before")
  require("./test2.js")
  console.log("test-after")
})
```
test2.js:
```javascript
console.log("test2-before")
a = require("nonexistantmodule")
console.log("test2-after")
```
Node and co versions:
```
$ node --version
v0.12.7
$ npm list co
/home/me
└── co@4.6.0 
```
Program output:
```
$ node test.js
test-before
test2-before
```
Expected output:
```
$ node test.js
test-before
test2-before
module.js:338
    throw err;
          ^
Error: Cannot find module 'nonexistantmodule'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/me/app/test2.js:2:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by bucaran** [comment]
```js
var co = require("co")
co(function()
{
  console.log("test-before")
  require("./test2.js")
  console.log("test-after")
}).catch(function (e) {
  throw e
}
```

**Comment by yetanotherusernamebecausegithubisbugged** [comment]
Tried your example, still no output.

**Comment by bucaran** [comment]
Updated.

**Comment by bucaran** [comment]
```
> require("co")(function *() {
... require("bad-module")
... }).catch(function (e) {
... console.log(e)
... })
Promise { <pending> }
> { [Error: Cannot find module 'bad-module'] code: 'MODULE_NOT_FOUND' }
```

**Comment by yetanotherusernamebecausegithubisbugged** [comment]
@bucaran, thank you, now it works. Issue is closed, I guess. Sorry for the disturbance.

**Comment by bucaran** [comment]
@yetanotherusernamebecausegithubisbugged It's tricky. :+1:
