### ISSUE TITLE
Useless stacktraces

### ISSUE THREAD

**Issue by faiwer** [tj/co#252]
Content of `index.js`

```js
"use strict";

let co = require('co');

co(function * ()
	{
		require('./bad.js');
	})
	.catch(err =>
	{
		console.log(err.message);
		console.log(err.stack);
	});
```

Content of `bad.js` with syntax error

```js
some syntax error
```

Finally stack trace

```
Unexpected identifier
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/faiwer/tmp/co/index.js:7:3
    at next (native)
    at onFulfilled (…/node_modules/co/index.js:65:19)
```

vm.js, module.js, etc…
what I need do for view equal that?

```
…/bad.js:1
(function (exports, require, module, __filename, __dirname) { some syntax error
                                                                        ^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    …
```

I want know line number, filename.

**Comment by faiwer** [comment]
Hm...

```js
function * gen()
	{
		try { require('./bad.js'); }
		catch(e)
		{
			console.log(e.message);
			console.log(e.stack);
		}
	}

	gen().next();
```

Also not return linenumber and filename.
