### ISSUE TITLE
Exceptions in catch blocks not properly handled

### ISSUE THREAD

**Issue by nschloe** [tj/co#254]
The node script
```js
const co = require('co');

co(function* main() {
  throw new Error('throw');
}).catch((err) => {
  console.log('hi');
  throw new Error('silence');
});
```
prints
```
hi
```
No trace of `Error('silence')`.

This is opposed to traditional JS
```js
try {
  throw new Error('throw');
} catch(err) {
  console.log('hi');
  throw new Error('silence');
}
```
which prints
```
hi
/tmp/w/test2.js:5
  throw new Error('silence');
  ^

Error: silence
    at Object.<anonymous> (/tmp/w/test2.js:5:9)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by vincentngthu** [comment]
This should work
```javascript
const co = require('co');

co(function* main() {
  throw new Error('throw');
}).catch((err) => {
  console.log('hi');
  throw new Error('silence');
}).then(null,console.error);
```

**Comment by nschloe** [comment]
Thanks for the reply.

I see that throwing inside Promise catchers is a tricky business, cf. http://stackoverflow.com/q/30715367/353337. Know that we do actually deal with Promises here, I'm inclined to say that the described behavior isn't co's fault.

Closing.
