### ISSUE TITLE
co and yield* when a promise is rejected ?

### ISSUE THREAD

**Issue by rehia** [tj/co#284]
I just faced an issue mixing generators and `yield*`, co, and node.
It seemed to be the right place to start, but I'm not really sure this is a problem with co.
Let me explain:

I usually use this code to make the node task fail whenever an error occurs in a generators chain handled by co, because of `Promise` specification, where errors are muted if not handled:
```js
process.on('unhandledRejection', (reason, p) => {
  throw reason;
});
```
I also find `yield*` a cleaner way to yield the values returned by an array of promises, instead of `Promise.all()`.
At first, I thought that it pretty did the same thing as `Promise.all()`, but when one of the promises is rejected, then I had the following error:
```
/somewhere/yield.js:14
  throw reason;
  ^
unhandled TypeError: Cannot read property 'done' of undefined
    at next (/somewhere/node_modules/co/index.js:98:14)
    at onRejected (/somewhere/node_modules/co/index.js:85:7)
    ....
```

Here is the full code:
https://gist.github.com/rehia/6b13bd8202a37fbb58c82cbdd9df9b83

I use Node 6.3.1 and co 4.6.0.
http://node.green/#generators tells that `yield*` is fully supported by Node... 
If you have any thoughts on this, I'll be glad to know :)

**Comment by rehia** [comment]
hi all, any idea about this ?
would love to share about this !

**Comment by targos** [comment]
You can only use `yield*` to delegate to other generators in `co`. The reason is that the `throw` call (made by `co` because of the rejected promise) is propagated to the array iterator and this iterator does not implement a `throw` method.

See https://bugs.chromium.org/p/v8/issues/detail?id=3484

The solution to your problem is just to use [`yield array`](https://github.com/tj/co#arrays)

**Comment by v-limliu** [comment]
the same to me , how to reject a error with co?  since only yield is used ,is  there anyway to do this
